### ISSUE TITLE
Add bannedAgencies parameter

### ISSUE THREAD

**Issue by Hussein-Mahfouz** [ropensci/opentripplanner#51]
Hi, first off thank you for the brilliant package! I am new to R and this made my life very easy.

I wanted to suggest adding the **bannedAgencies** parameter to the otp_plan() and otp_isochrone() functions. This exists in [OpenTripPlanner ](http://dev.opentripplanner.org/apidoc/1.0.0/resource_PlannerResource.html). One use case I can think of is informal transit; you have formal buses and informal buses which both go under mode “BUS”, but are normally under different agencies. This is specific to cities in developing countries (I was working on Cairo, Egypt)

It would be something like this:

```
otp_isochrone(
      otpcon = otpcon, 
      fromPlace = c(-0.1346, 51.5292),
      mode = "TRANSIT",
      date_time = Sys.time(),
      maxWalkDistance = 800,
      cutoffSec = 3600
      bannedAgencies = c("Microbus", "Suzuki") 
)
```
In this case, _Microbus_ and _Suzuki_ are informal modes of transport that fall under the mode "BUS", so they cannot be filtered out by the mode parameter. 

For my work, I ended up using the [onebusaway-gtfs-transformer-cli](http://developer.onebusaway.org/modules/onebusaway-gtfs-modules/1.3.4-SNAPSHOT/onebusaway-gtfs-transformer-cli.html) to subset the GTFS by agency, but this required building a new otp graph with the subsetted GTFS. The bannedAgencies parameter would allow the analysis to be done on the same graph.

**Comment by mem48** [comment]
Good suggestion I'll look into it. In the meantime you may be able to get the same effect with the config files see otp_make_config()

**Comment by mem48** [comment]
@Hussein-Mahfouz  I've added this feature and a bunch more in a new branch https://github.com/ropensci/opentripplanner/tree/batch-isochrone let me know if it works for you. You can specify the bannedAgencies by using the routingOptions argument and the new functions otp_routing_options() and otp_validate_routing_options()

**Comment by Hussein-Mahfouz** [comment]
@mem48 I see that you've added all the otp arguments to the otp_routing_options() function. This is fantastic! 

I tried to test it but was unable to; I get a 'could not find function "otp_routing_options" ' error (I installed the development version of the package). Am I doing something wrong or is this function not available yet? I apologize if this is a silly question

**Comment by mem48** [comment]
Did you install the correct branch? You would need to do `remotes::install_github("ropensci/opentripplanner", ref = "batch-isochrone")`

**Comment by Hussein-Mahfouz** [comment]
Oh thank you, my bad. I tried the bannedAgencies argument and it works when I add one agency to the bannedAgencies argument. However when I tried to add a list of agencies I get the following error:

`Error in vapply(elements, encode, character(1)) : 
  values must be length 1,
 but FUN(X[[8]]) result is length 2`

This is how I am passing the argument
```
routingOptions <- otp_routing_options()
routingOptions$bannedAgencies <- c("firstAgency", "secondAgency")
routingOptions <- otp_validate_routing_options(routingOptions)
```
Am I doing something wrong?

**Comment by mem48** [comment]
yes, you need to pass a single character string, exactly as required by the OTP API http://dev.opentripplanner.org/apidoc/1.4.0/resource_PlannerResource.html I haven't implemented any interpretation of the inputs. So I think `routingOptions$bannedAgencies <- "firstAgency,secondAgency"` should work.

**Comment by mem48** [comment]
I've just pushed an update to `otp_validate_routing_options()` it should now give a warning that the length should be 1.

**Comment by Hussein-Mahfouz** [comment]
It works now! It didn't at first but then I realized that there should be no spaces in the character string

**Comment by mem48** [comment]
Great, if you have any other feedback on how routing options could be improved let me know. Otherwise I will close this issue.

**Comment by Hussein-Mahfouz** [comment]
I have no more feedback now :)

**Comment by Robinlovelace** [comment]
I think this can be closed - please do so @Hussein-Mahfouz unless this is still an issue.
